/*
 * This source file was generated by the Gradle 'init' task
 */
package sim;

import sim.network.topology.DirectedCM;
import sim.network.DirectedGraph;

public class App {
    public static void main(String[] args) {
        int n = 1000;
        int kHat = 10;
        long seed = 1234567890;
        DirectedGraph g = DirectedCM.generate("test", n, kHat, seed);
        g.printInfo();
    }
}
