/*
 * This source file was generated by the Gradle 'init' task
 */
package sim;

import sim.network.topology.DirectedCM;
import sim.network.DirectedGraph;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void testDirectedCM() {
        int n = 1000;
        int kHat = 10;
        long seed = 1234567890;
        DirectedGraph g = DirectedCM.generate("test", n, kHat, seed);
        g.printInfo();
    }
}
